name: wallet
description: hệ thống quản lý ví tiền mã hoá

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0
  flutter: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  provider: ^6.0.0
  web3dart: ^2.3.0
  http: ^0.13.6
  english_words: ^4.0.0
  mockito: ^5.0.0
  mongo_dart: ^0.9.4
  qr_flutter: ^4.1.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  mobile_scanner: ^6.0.7
  flutter_secure_storage: ^8.0.0 # Use the latest version
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/vi.json